### ISSUE TITLE
When running 4-Run_REAL.py, the file seqt_real_catalog_sel.txt is not found.

### ISSUE THREAD

**Issue by PANGAOTIAN** [SigProSeismology/IPIML#1]
Hi, when I run the code 4-Run_REAL.py, why do I get this error:
 Traceback (most recent call last).
  File "/mnt/d/wsl/IPIML-main/4-Run_REAL.py", line 241, in <module
    runREAL(cfgs)
  File "/mnt/d/wsl/IPIML-main/4-Run_REAL.py", line 142, in runREAL
    os.rename('. /catalog_sel.txt', '{}seqt_real_catalog_sel.txt'.format(cfgs['REAL']['seqt_catalog_dir']))
FileNotFoundError: [Errno 2] No such file or directory: '. /catalog_sel.txt' -> '. /SEqTCatalogs/seqt_real_catalog_sel.txt'. I have searched the file and can't find the file in question can you tell me why, thank you!

Translated with DeepL.com (free version)

**Comment by SigProSeismology** [comment]
Hello, it appears that the 4-Run_REAL.py script is not generating the ./catalog_sel.txt file on your system. This issue is likely due to the compiled binary 'REAL' not functioning properly on your system. The initial solution for you is to navigate to the ./IPIML/REALL/ directory, delete the 'REAL' binary, and then execute the 'make' command to recompile it. Hope it works!
Please let me know if not.

**Comment by PANGAOTIAN** [comment]
Thank you for your answer, I ran the program 4-Run_REAL.py successfully as you said, but when running 5-Run_MIL.py, I encountered a new problem: 
  Traceback (most recent call last):
  File "/mnt/d/download/IPIML-main/5-Run_MIL.py", line 37, in <module>.
    coseismiq = MALMI(cfgs=cfgs)
  File "/mnt/d/download/IPIML-main/. /src/mainMALMI.py", line 409 in __init__
    grid = build_traveltime(grid, tt, self.stainv)
  The file "/mnt/d/downloads/IPIML-main/. /src/traveltime.py", line 187 in build_traveltime
    subprocess.run(["Vel2Grid", inpara['filename']]) # Call the NonLinLoc Vel2Grid program to generate the velocity grid
  File "/home/pangyan/miniconda3/envs/IPIML/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pangyan/miniconda3/envs/IPIML/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/pangyan/miniconda3/envs/IPIML/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Vel2Grid'.
I'm very confused about this problem,  do you know how to fix it?
